# Generated by Django 5.2.12 on 2026-07-05 20:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pcode', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Level 1',
            },
        ),
        migrations.CreateModel(
            name='Admin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pcode', models.CharField(max_length=20, unique=True)),
                ('admin1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin2s', to='fields_admin.admin1')),
            ],
            options={
                'verbose_name_plural': 'Admin Level 2',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('crop', models.CharField(choices=[('Maize', 'Maize'), ('Groundnuts', 'Groundnuts'), ('Soybeans', 'Soybeans'), ('Cotton', 'Cotton'), ('Tobacco', 'Tobacco'), ('Sunflower', 'Sunflower'), ('Sorghum', 'Sorghum'), ('Millet', 'Millet'), ('Beans', 'Beans'), ('Potatoes', 'Potatoes'), ('Tomatoes', 'Tomatoes'), ('Other', 'Other')], default='Maize', max_length=50)),
                ('production_system', models.CharField(choices=[('Rainfed', 'Rainfed'), ('Irrigated', 'Irrigated')], default='Rainfed', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_ha', models.FloatField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adm1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fields_admin.admin1')),
                ('adm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fields_admin.admin2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
