# Generated by Django 5.2.12 on 2026-07-30 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields_admin', '0002_rainfallprovince'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldNDVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_records', to='fields_admin.field')),
            ],
            options={
                'verbose_name_plural': 'Field NDVI Records',
                'ordering': ['-date'],
                'unique_together': {('field', 'date')},
            },
        ),
    ]
