# Generated by Django 5.2.12 on 2026-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields_admin', '0003_fieldndvi'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(db_index=True, help_text='Province or town name', max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('ndvi_value', models.FloatField(default=0.0, help_text='NDVI value (-1 to 1)')),
                ('lat', models.FloatField(blank=True, help_text='Latitude', null=True)),
                ('lng', models.FloatField(blank=True, help_text='Longitude', null=True)),
                ('cloud_cover', models.FloatField(blank=True, help_text='Cloud cover percentage', null=True)),
                ('source', models.CharField(default='Sentinel-2', help_text='Data source', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'NDVI Data',
                'ordering': ['-date', 'province'],
                'unique_together': {('province', 'date')},
            },
        ),
    ]
